Restaurant/force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Restaurant/force-app/main/default/objects/Employee__c/fields/End_Employment_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Employment_Date__c</fullName>
    <description>If the employee no longer works at the company, displays what date they left</description>
    <inlineHelpText>Enter the date the employee left employment on - only managers can create this</inlineHelpText>
    <label>End Employment Date</label>
    <type>Date</type>
</CustomField>

Restaurant/force-app/main/default/objects/Employee__c/fields/Hired_On_Date__c.field-meta.xml
<CustomField>
    <fullName>Hired_On_Date__c</fullName>
    <description>The date the employee was hired on</description>
    <inlineHelpText>Enter the date the employee was hired on - only managers can create</inlineHelpText>
    <label>Hired On Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

Restaurant/force-app/main/default/objects/Employee__c/fields/Salary__c.field-meta.xml
<CustomField>
    <fullName>Salary__c</fullName>
    <description>The employees salary</description>
    <inlineHelpText>Enter the Employees salary in this field - only managers can edit this field</inlineHelpText>
    <label>Salary</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

Restaurant/force-app/main/default/classes/EmployeeTriggerTest.cls
@isTest
private class EmployeeTriggerTest {
    @TestSetup
    static void makeData(){
        List<Employee__c> employees = new List<Employee__C>();
        for(Integer i = 0; i < 99; i++) {
            Date d = Date.newInstance(2020, 10, 5);
            employees.add(new Employee__c(Name = 'Employee '+i, Salary__c = 50, Hired_On_Date__c = d, End_Employment_Date__c = NULL));
        }
        for(Integer i = 0; i < 99; i++) {
            Date d = Date.newInstance(2020, 10, 5);
            Date d2 = Date.newInstance(2020, 11, 5);
            employees.add(new Employee__c(Name = 'Past Employee '+i, Salary__c = 50, Hired_On_Date__c = d, End_Employment_Date__c = d2));
        }
        
        insert employees;
    }

    @isTest static void singleTest() {
        Test.startTest();
		
		Employee__c eSuccess = [SELECT Id, Salary__c, End_Employment_Date__c FROM Employee__c WHERE Name = 'Employee 1' LIMIT 1];
        Employee__c eFail = [SELECT Id, Salary__c, End_Employment_Date__c FROM Employee__c WHERE Name = 'Past Employee 1' LIMIT 1];
        
        eSuccess.Salary__c = 500;
        Database.SaveResult srSuccess = Database.update(eSuccess, false);
        
        eFail.Salary__c = 500;
        Database.SaveResult srFail = Database.update(eFail, false);
        
        Integer numSuccess = 0;
        Integer numFail = 0;
        if(srSuccess.isSuccess()) {
            numSuccess++;
        }
        if(!srFail.isSuccess()) {
            numFail++;
        }
        
        System.assertEquals(1, numSuccess);
        System.assertEquals(1, numFail);

        Test.stopTest();
    }

    @isTest static void bulkTest() {
        Test.startTest();

		List<Employee__c> employees = [SELECT Id, Salary__c, End_Employment_Date__c FROM Employee__c WHERE End_Employment_Date__c = NULL OR End_Employment_Date__c != NULL];
        for(Employee__c e: employees) {
            e.Salary__c = 500;
        }
        
        List<Database.SaveResult> srs = Database.update(employees, false);
        
        Integer numSuccess = 0;
        Integer numFail = 0;
        for(Database.SaveResult sr: srs) {
            if(sr.isSuccess()) {
                numSuccess++;
            } else {
                numFail++;
            }
        }
        
        System.assertEquals(99, numSuccess);
        System.assertEquals(99, numFail);

        Test.stopTest();
    }
}