Restaurant/force-app/main/default/objects/Contact/fields/Picture_URL__c.field-meta.xml
<CustomField>
    <fullName>Picture_URL__c</fullName>
    <label>Picture URL</label>
    <type>Url</type>
</CustomField>

Restaurant/force-app/main/default/objects/Contact/fields/Transactions__c.field-meta.xml
<CustomField>
    <fullName>Transactions__c</fullName>
    <label>Transactions</label>
    <summaryForeignKey>Transaction__c.Contact__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

Restaurant/force-app/main/default/classes/contactExtension.cls
public class contactExtension {
    
    public boolean showCustOfWeek{get;set;} 
    public Contact mycon {get; set;}
    
	public contactExtension(ApexPages.StandardSetController stdController ) {
        mycon = [Select FirstName, LastName, Picture_URL__c, Transactions__c, Gender__c from Contact order by Transactions__c Desc limit 1][0];
        showCustOfWeek = false;
    }
    
    public void CustOFWeek(){
        showCustOfWeek = !showCustOfWeek;

    }
}