Restaurant/force-app/main/default/objects/Distribution_Contract__c/Distribution_Contract__c.object-meta.xml
<CustomObject>
    <label>Distribution Contract</label>
    <nameField>
        <label>Distributor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Distribution Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Restaurant/force-app/main/default/objects/Distribution_Contract__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Distribution Contracts</relationshipLabel>
    <relationshipName>Distribution_Contracts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

Restaurant/force-app/main/default/objects/Distribution_Contract__c/fields/Cost__c.field-meta.xml
<CustomField>
    <fullName>Cost__c</fullName>
    <description>agreed on cost of the products distributed</description>
    <label>Cost</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

Restaurant/force-app/main/default/objects/Distribution_Contract__c/fields/Distributor__c.field-meta.xml
<CustomField>
    <fullName>Distributor__c</fullName>
    <label>Distributor</label>
    <referenceTo>Distributor__c</referenceTo>
    <relationshipLabel>Distribution Contracts</relationshipLabel>
    <relationshipName>Distribution_Contracts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Restaurant/force-app/main/default/objects/Distribution_Contract__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

Restaurant/force-app/main/default/objects/Distribution_Contract__c/fields/Product_Count__c.field-meta.xml
<CustomField>
    <fullName>Product_Count__c</fullName>
    <label>Product Count</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Restaurant/force-app/main/default/objects/Distributor__c/Distributor__c.object-meta.xml
<CustomObject>
    <label>Distributor</label>
    <nameField>
        <label>Distributor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Distributors</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Restaurant/force-app/main/default/objects/Distributor__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Distributors</relationshipLabel>
    <relationshipName>Distributors</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Restaurant/force-app/main/default/classes/DistributionContractTriggerTest.cls
@isTest
private class DistributionContractTriggerTest {
    @TestSetup
    static void makeData(){
        
        List<Distribution_Contract__c> dContracts = new List<Distribution_Contract__c>();
        Account a = new Account(name='hi');
        Distributor__c d = new Distributor__c(name='hi');
        insert a;
        insert d;
        a = [SELECT Id FROM Account WHERE Name = 'hi' LIMIT 1];
        d = [SELECT Id FROM Distributor__c WHERE Name = 'hi' LIMIT 1];
        for(Integer i = 0; i < 100; i++) {
            Distribution_Contract__c aDContract = new Distribution_Contract__c(Name = 'true contracts', Is_Active__c = true, Account__c = a.Id, Distributor__c = d.Id, Cost__c = 5, Product_Count__c = 5);
            dContracts.add(aDContract);
        }
        for(Integer i = 0; i < 100; i++) {
            Distribution_Contract__c aDContract = new Distribution_Contract__c(Name = 'false contracts', Is_Active__c = false, Account__c = a.Id, Distributor__c = d.Id, Cost__c = 5, Product_Count__c = 5);
            dContracts.add(aDContract);
        }

        insert dContracts;
    }

    @isTest static void singleTest() {
        Test.startTest();
        Account a = [SELECT Id FROM Account WHERE Name = 'hi' LIMIT 1];
        Distributor__c d = [SELECT Id FROM Distributor__c WHERE Name = 'hi' LIMIT 1];
        
        // Test Success on one record
        Distribution_Contract__c aDistContract = new Distribution_Contract__c(Name = 'test contract', Is_Active__c = false, Account__c = a.Id, Distributor__c = d.Id, Cost__c = 5, Product_Count__c = 5);
        insert aDistContract;
        Database.DeleteREsult dr1 = Database.delete(aDistContract, false);
        Integer numSuccess = 0;
        if(dr1.isSuccess()) {
            numSuccess = 1;
        }
        
        // Test Fail on one record
        Distribution_Contract__c aDistContract2 = new Distribution_Contract__c(Name = 'test contract', Is_Active__c = true, Account__c = a.Id, Distributor__c = d.Id, Cost__c = 5, Product_Count__c = 5);
        insert aDistContract2;
        Database.DeleteResult dr = Database.delete(aDistContract, false);
        Integer numFail = 0;
        if(!dr.isSuccess()) {
            numFail = 1;
        }
        System.assertEquals(1, numFail);
        System.assertEquals(1, numSuccess);
        Test.stopTest();
    }

    @isTest static void bulkTest() {
		Test.startTest();
        Account a = [SELECT Id FROM Account WHERE Name = 'hi' LIMIT 1];
        Distributor__c d = [SELECT Id FROM Distributor__c WHERE Name = 'hi' LIMIT 1];
        
        List<Distribution_Contract__c> distrContractsSuccess = new List<Distribution_Contract__c>();
        List<Distribution_Contract__c> distrContractsFail = new List<Distribution_Contract__c>();
        
        for(Integer i = 0; i < 200; i++) {
            Distribution_Contract__c aDContract = new Distribution_Contract__c(Name = 'true contracts', Is_Active__c = true, Account__c = a.Id, Distributor__c = d.Id, Cost__c = 5, Product_Count__c = 5);
            distrContractsFail.add(aDContract);
        }
        for(Integer i = 0; i < 200; i++) {
            Distribution_Contract__c aDContract = new Distribution_Contract__c(Name = 'false contracts', Is_Active__c = false, Account__c = a.Id, Distributor__c = d.Id, Cost__c = 5, Product_Count__c = 5);
            distrContractsSuccess.add(aDContract);
        }
        
        insert distrContractsFail;
        insert distrContractsSuccess;
        
        List<Database.deleteResult> drsSuccess = Database.delete(distrContractsSuccess, false);
        List<Database.deleteResult> drsFail = Database.delete(distrContractsFail, false);

        Integer numSuccess = 0;
        for(Database.DeleteResult dr: drsSuccess) {
            if(dr.isSuccess()) {
                numSuccess++;
            }
        }
        Integer numFail = 0;
        for(Database.DeleteResult dr: drsFail) {
            if(!dr.isSuccess()) {
                numFail++;
            }
        }
        
        System.assertEquals(200, numSuccess);
        System.assertEquals(200, numFail);
        
        Test.stopTest();
    }
    
    @isTest static void bulkTestMix() {
        Test.startTest();
        Account a = [SELECT Id FROM Account WHERE Name = 'hi' LIMIT 1];
        Distributor__c d = [SELECT Id FROM Distributor__c WHERE Name = 'hi' LIMIT 1];
        
        List<Distribution_Contract__c> distrContracts = new List<Distribution_Contract__c>();
        
        for(Integer i = 0; i < 100; i++) {
            Distribution_Contract__c aDContract = new Distribution_Contract__c(Name = 'true contracts', Is_Active__c = true, Account__c = a.Id, Distributor__c = d.Id, Cost__c = 5, Product_Count__c = 5);
            distrContracts.add(aDContract);
        }
        for(Integer i = 0; i < 100; i++) {
            Distribution_Contract__c aDContract = new Distribution_Contract__c(Name = 'false contracts', Is_Active__c = false, Account__c = a.Id, Distributor__c = d.Id, Cost__c = 5, Product_Count__c = 5);
            distrContracts.add(aDContract);
        }
        
        insert distrContracts;
        
        Integer numFails = 0;
        Integer numSuccess = 0;
        List<Database.DeleteResult> drs = Database.delete(distrContracts, false);
        for(Database.DeleteResult dr: drs) {
            if(!dr.isSuccess()) {
                numFails++;
            } else {
                numSuccess++;
            }
        }
        
        System.assertEquals(100, numFails);
        System.assertEquals(100, numSuccess);
        
        Test.stopTest();
    }
}