Restaurant/force-app/main/default/objects/Distribution_Contract__c/Distribution_Contract__c.object-meta.xml
<CustomObject>
    <label>Distribution Contract</label>
    <nameField>
        <label>Distributor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Distribution Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Restaurant/force-app/main/default/objects/Distribution_Contract__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Distribution Contracts</relationshipLabel>
    <relationshipName>Distribution_Contracts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

Restaurant/force-app/main/default/objects/Distribution_Contract__c/fields/Cost__c.field-meta.xml
<CustomField>
    <fullName>Cost__c</fullName>
    <description>agreed on cost of the products distributed</description>
    <label>Cost</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

Restaurant/force-app/main/default/objects/Distribution_Contract__c/fields/Distributor__c.field-meta.xml
<CustomField>
    <fullName>Distributor__c</fullName>
    <label>Distributor</label>
    <referenceTo>Distributor__c</referenceTo>
    <relationshipLabel>Distribution Contracts</relationshipLabel>
    <relationshipName>Distribution_Contracts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Restaurant/force-app/main/default/objects/Distribution_Contract__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

Restaurant/force-app/main/default/objects/Distribution_Contract__c/fields/Product_Count__c.field-meta.xml
<CustomField>
    <fullName>Product_Count__c</fullName>
    <label>Product Count</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Restaurant/force-app/main/default/objects/Distributor__c/Distributor__c.object-meta.xml
<CustomObject>
    <label>Distributor</label>
    <nameField>
        <label>Distributor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Distributors</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Restaurant/force-app/main/default/objects/Distributor__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Distributors</relationshipLabel>
    <relationshipName>Distributors</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Restaurant/force-app/main/default/classes/DistributorController.cls
global class DistributorController {
    
    public String csvParam {get; set;}
    public String csvResult {get; set;}
    
    public List<Distributor__c> getDistributors(){
        List<Distributor__c> ret = [SELECT id, Name FROM Distributor__c];
        return ret;
    }
    
    public void csvFactory(){
        csvResult = '';
        System.debug(csvParam);
        Distributor__c d = Database.query('SELECT id, Name, (SELECT id, Name, Is_Active__c, Account__c, Cost__c, Product_Count__c FROM Distribution_Contracts__r) FROM Distributor__c WHERE id = :csvParam LIMIT 1');
        
        
        //List<Distribution_Contract__c> dcs = new List<Distribution_Contract__c>();
        
        List<Distribution_Contract__c> dcs = d.Distribution_Contracts__r;
        
        //for(Distribution_Contract__c dc: d.Distribution_Contract__r){ 
        //    dcs.add(dc);
        //}
        
        
        String row = '';
        String csv = '';
        
        for(Distribution_Contract__c dc: dcs){
            row = dc.id;
            row = row + ', ' + dc.Account__c;
            row = row + ', ' + d.Name;
            row = row + ', ' + dc.Name;
            row = row + ', ' + dc.Product_Count__c;
            row = row + ', ' + dc.Cost__c;
            row = row + ', ' + dc.Is_Active__c;
            csvResult = csvResult + row + '<br>';
        }  
    }
}

/* 
public with sharing class DistributorController {
    public List<Distributor__c> getDistributors(){
        List<Distributor__c> ret = [SELECT id, Name FROM Distributor__c];
        return ret;
    }
}
*/