Restaurant/force-app/main/default/objects/Food__c/Food__c.object-meta.xml
<CustomObject>
    <label>Food</label>
    <nameField>
        <label>Food Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Foods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Restaurant/force-app/main/default/objects/Food__c/fields/Stock_Amount__c.field-meta.xml
<CustomField>
    <fullName>Stock_Amount__c</fullName>
    <label>Stock Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Restaurant/force-app/main/default/objects/Meal__c/Meal__c.object-meta.xml
<CustomObject>
    <label>Meal</label>
    <nameField>
        <label>Meal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Restaurant/force-app/main/default/objects/Meal__c/fields/Food__c.field-meta.xml
<CustomField>
    <fullName>Food__c</fullName>
    <label>Food</label>
    <referenceTo>Food__c</referenceTo>
    <relationshipLabel>Meals</relationshipLabel>
    <relationshipName>Meals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Restaurant/force-app/main/default/objects/Meal__c/fields/Food_Recipe_Amount__c.field-meta.xml
<CustomField>
    <fullName>Food_Recipe_Amount__c</fullName>
    <label>Food Recipe Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Restaurant/force-app/main/default/classes/MealTriggerHandler.cls
public with sharing class MealTriggerHandler {
    public static void checkIfOutOfStock(list<Meal__c> insertMeals) {
        List<Food__c> Foods = [SELECT Id, Stock_Amount__c FROM Food__c];
        Map<Meal__c, Food__c> foodMealMap = new Map<Meal__c,Food__c>();

        for(Meal__c aMeal: insertMeals) {
            for(Food__c aFood: Foods) {
                if(aMeal.Food__c == aFood.Id) {
                    foodMealMap.put(aMeal, aFood);
                }
            }
        }

        for(Meal__c aMeal: foodMealMap.keySet()) {
            if(aMeal.Food_Recipe_Amount__c > foodMealMap.get(aMeal).Stock_Amount__c) {
                aMeal.addError('Cannot Insert Meal, Out of Stock on the Food');
            }
        }
    }
}