Restaurant/force-app/main/default/objects/Food__c/Food__c.object-meta.xml
<CustomObject>
    <label>Food</label>
    <nameField>
        <label>Food Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Foods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Restaurant/force-app/main/default/objects/Food__c/fields/Stock_Amount__c.field-meta.xml
<CustomField>
    <fullName>Stock_Amount__c</fullName>
    <label>Stock Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Restaurant/force-app/main/default/classes/FoodController.cls
public class FoodController {
    public List<Food__c> foods {get; set;}
    
    public FoodController() {
        this.foods = [select name, stock_amount__c from food__c];
    }

    public void increaseStock() {
        this.foods[0].stock_amount__c++;
        update this.foods;
    }

    public void decreaseStock() {
        if (this.foods[0].stock_amount__c != 0) {
            this.foods[0].stock_amount__c--;
        }
        update this.foods;
    }
}